albums/urls.py
from django.urls import path

from . import views

app_name = 'albums'

urlpatterns = [
    path(r'album_info/<str:album_id>/', views.album_info, name='album_info'),
]

artists/urls.py
from django.urls import path

from . import views

app_name = 'artists'

urlpatterns = [
    path(r'my_artists/', views.all_artists, name='my_artists', kwargs={'mine': True}),
    path(r'all_artists/', views.all_artists, name='all_artists'),
    path(r'user_artists/<str:user_id>/', views.all_artists, name='user_artists'),
    path(r'single_artist/<str:artist_id>/', views.single_artist, name='single_artist'),
]

base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'spotify_login/', views.spotify_login, name='login'),
    path(r'callback/', views.spotify_callback, name='callback'),
    path(r'pull_data/', views.pull_data, name='pull_data'),
    path(r'logout/', views.logout_view, name='logout'),
]

spotify_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('base.urls')),
    re_path(r'^artists/', include('artists.urls')),
    re_path(r'^tracks/', include('tracks.urls')),
    re_path(r'^libraries/', include('libraries.urls')),
    re_path(r'^albums/', include('albums.urls')),
    re_path(r'^users/', include('users.urls')),
    re_path(r'^playlists/', include('playlists.urls')),
]

tracks/urls.py
from django.urls import path

from . import views

app_name = 'tracks'

urlpatterns = [
    path(r'track_info/<str:track_id>/', views.track_info, name='track_info'),
]

albums/models.py
from django.db import models


class Album(models.Model):
    objects = models.Manager()
    spotify_id = models.CharField(max_length=100, primary_key=True)
    name = models.CharField(max_length=200)
    artists = models.ManyToManyField('artists.Artist', related_name='albums')
    release_date = models.CharField(max_length=10)

    def __str__(self):
        return self.name

albums/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from albums.models import Album


@login_required
def album_info(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(
        request,
        'album_info.html',
        {'album': album},
    )

albums/templates/album_info.html
{% extends "base.html" %}
{% block title %}Album: {{ album.name }}{% endblock title %}
{% block content %}
    <div class="container">
        <div class="text-center" style="padding-bottom:65px">
            <h1>Album Info</h1>
        </div>
        <dl class="row properties">
            <dt class="col-sm-3">Title</dt>
            <dd class="col-sm-9" id="album-name">{{ album.name }}</dd>
            <dt class="col-sm-3">Artists</dt>
            <dd class="col-sm-9" id="artists">
                <ul class="list-group">
                {% for artist in album.artists.all|dictsort:"name" %}
                    <li class="list-group-flush artist-name">
                        <a href="{% url 'artists:single_artist' artist.spotify_id %}">
                            {{ artist.name }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            </dd>
            <dt class="col-sm-3">Tracks</dt>
            <dd class="col-sm-9" id="tracks">
                <ul class="list-group">
                {% for track in album.tracks.all|dictsort:"name" %}
                    <li class="list-group-flush track-name">
                        <a href="{% url 'tracks:track_info' track.spotify_id %}">
                            {{ track.name }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            </dd>
            <dt class="col-sm-3">ID</dt>
            <dd class="col-sm-9" id="album-id">{{ album.spotify_id }}</dd>
            <dt class="col-sm-3">Release Date</dt>
            <dd class="col-sm-9" id="release-date">{{ album.release_date }}</dd>
        </dl>
    </div>
{% endblock content %}