base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'spotify_login/', views.spotify_login, name='login'),
    path(r'callback/', views.spotify_callback, name='callback'),
    path(r'pull_data/', views.pull_data, name='pull_data'),
    path(r'logout/', views.logout_view, name='logout'),
]

libraries/urls.py
from django.urls import path

from . import views

app_name = 'libraries'

urlpatterns = [
    path(r'library_stats/<str:user_id>/', views.library_stats, name='library_stats'),
    path(
        r'library_stats/',
        views.library_stats,
        name='my_library_stats',
        kwargs={'user_id': None},
    ),
    path(
        r'compare_stats/',
        views.compare_stats,
        name='compare_stats',
    ),
    path(
        r'browse_libraries/',
        views.browse_libraries,
        name='browse_libraries',
    ),
]

spotify_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('base.urls')),
    re_path(r'^artists/', include('artists.urls')),
    re_path(r'^tracks/', include('tracks.urls')),
    re_path(r'^libraries/', include('libraries.urls')),
    re_path(r'^albums/', include('albums.urls')),
    re_path(r'^users/', include('users.urls')),
    re_path(r'^playlists/', include('playlists.urls')),
]

users/urls.py
from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    path(r'my_info/', views.user_info, name='my_info'),
    path(r'user_info/<str:user_id>/', views.user_info, name='user_info'),
]

base/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.http import require_POST

from spotify import Spotify
from spotify.oauth import OAuth


# TODO login required. redirect to this
def index(request):
    if request.user.is_authenticated:
        return redirect(reverse('libraries:my_library_stats'))
    return render(request, 'index.html', {})


@require_POST
def spotify_login(request):
    oauth = OAuth()
    auth_url = oauth.create_auth_url()
    return redirect(auth_url)


def spotify_callback(request):
    oauth = OAuth()
    request.session['token_response'] = oauth.get_token_json(request)
    access_token = request.session['token_response']['access_token']
    user = authenticate(access_token=access_token)
    if user is not None:
        login(request, user)
        return redirect(reverse('libraries:my_library_stats'))
    return redirect(reverse('base:index'))


def logout_view(request):
    logout(request)
    return redirect(reverse('base:index'))


@require_POST
def pull_data(request):
    access_token = request.session['token_response']['access_token']
    spotify = Spotify(access_token)
    spotify.pull_library_data(request.user)
    return redirect(reverse('base:index'))

base/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'base:index' %}">MySpotifyTool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="libraryMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                            </a>
                            <ul class="dropdown-menu dropdown-menu-start" aria-labelledby="libraryMenu">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'libraries:my_library_stats' %}">My Library</a></li>
                            {% endif %}    
                                <li><a class="dropdown-item" href="{% url 'libraries:browse_libraries' %}">Browse Libraries</a></li>    
                            </ul>
                        </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="playlistMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Playlist
                            </a>
                            <ul class="dropdown-menu dropdown-menu-start" aria-labelledby="playlistMenu">
                                <li><a class="dropdown-item" href="">Foo</a></li>
                                <li><a class="dropdown-item" href="">Bar</a></li>    
                            </ul>
                        </li>
                    {% endif %}    
                    </ul>
                    <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userMenu">
                                <li><a class="dropdown-item" href="{% url 'users:my_info' %}">Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'libraries:my_library_stats' %}">My Library</a></li>
                                <div class="dropdown-divider"></div>
                                <li><a class="dropdown-item" href="{% url 'base:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'base:login' %}">Login</a></li>
                    {% endif %}  
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container" style="padding-top: 65px">
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>

base/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}
    <div class="text-center">
        <h1>Welcome</h1>
    </div>
    <form action="{% url 'base:login' %}" class="form" method="POST">
        <div class="row justify-content-center" style="padding-top: 65px">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary col-2 text-center">
                Login
            </button>
        </div>
    </form>
{% endblock content %}