artists/urls.py
from django.urls import path

from . import views

app_name = 'artists'

urlpatterns = [
    path(r'my_artists/', views.all_artists, name='my_artists', kwargs={'mine': True}),
    path(r'all_artists/', views.all_artists, name='all_artists'),
    path(r'user_artists/<str:user_id>/', views.all_artists, name='user_artists'),
    path(r'single_artist/<str:artist_id>/', views.single_artist, name='single_artist'),
]

base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'spotify_login/', views.spotify_login, name='login'),
    path(r'callback/', views.spotify_callback, name='callback'),
    path(r'pull_data/', views.pull_data, name='pull_data'),
    path(r'logout/', views.logout_view, name='logout'),
]

libraries/urls.py
from django.urls import path

from . import views

app_name = 'libraries'

urlpatterns = [
    path(r'library_stats/<str:user_id>/', views.library_stats, name='library_stats'),
    path(
        r'library_stats/',
        views.library_stats,
        name='my_library_stats',
        kwargs={'user_id': None},
    ),
    path(
        r'compare_stats/',
        views.compare_stats,
        name='compare_stats',
    ),
    path(
        r'browse_libraries/',
        views.browse_libraries,
        name='browse_libraries',
    ),
]

spotify_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('base.urls')),
    re_path(r'^artists/', include('artists.urls')),
    re_path(r'^tracks/', include('tracks.urls')),
    re_path(r'^libraries/', include('libraries.urls')),
    re_path(r'^albums/', include('albums.urls')),
    re_path(r'^users/', include('users.urls')),
    re_path(r'^playlists/', include('playlists.urls')),
]

users/urls.py
from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    path(r'my_info/', views.user_info, name='my_info'),
    path(r'user_info/<str:user_id>/', views.user_info, name='user_info'),
]

libraries/models.py
from collections import defaultdict
from datetime import timedelta
from operator import itemgetter

from django.conf import settings
from django.db import models


class Library(models.Model):
    objects = models.Manager()
    tracks = models.ManyToManyField('tracks.Track', related_name='libraries')
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='library',
    )
    artists = models.ManyToManyField('artists.Artist', related_name='libraries')
    last_updated = models.DateTimeField(auto_now_add=True, blank=True)

    @property
    def top_artists(self):
        artist_dict = defaultdict(int)
        for track in self.tracks.all().prefetch_related('artists'):
            for artist in track.artists.all():
                artist_dict[artist] += 1
        list_tuples = list(artist_dict.items())
        list_tuples.sort(key=itemgetter(1), reverse=True)
        result = dict(list_tuples[:10])
        return result

    @property
    def total_duration(self):
        result = 0
        for track in self.tracks.all():
            result += int(track.duration_ms)
        return timedelta(milliseconds=result)

    @property
    def avg_pop(self):
        total_pop = 0
        for track in self.tracks.all():
            total_pop += int(track.popularity)
        try:
            return round(total_pop / self.tracks.count(), 2)
        except ZeroDivisionError:
            return 0

libraries/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from libraries.models import Library
from users.forms import UserForm
from users.models import CustomUser


def library_stats(request, user_id):
    if user_id is None:
        library = request.user.library
    else:
        library = get_object_or_404(Library, user=user_id)
    return render(request, 'library_stats.html', {'library': library})


@login_required
def compare_stats(request):
    form = UserForm(me=request.user)
    context = {
        'my_library': request.user.library,
    }
    if request.GET:
        form = UserForm(request.GET, me=request.user)
        if form.is_valid():
            context['their_library'] = form.cleaned_data['user'].library
    context['form'] = form
    return render(request, 'compare_stats.html', context)


def browse_libraries(request):
    form = UserForm()
    library = None
    if request.GET:
        form = UserForm(request.GET)
        if form.is_valid():
            user = form.cleaned_data['user']
            library = user.library
    context = {
        'form': form,
        'library': library,
    }
    return render(request, 'library_stats.html', context)

libraries/templates/compare_stats.html
{% extends "base.html" %}
{% load date_utils %}
{% load diff_utils %}
{% block title %}Compare Library Stats{% endblock title %}
{% block content %}
  <div class="container">
    <div class="text-center" style="padding-bottom:35px">
      <h1 style="padding-bottom:35px">Compare Library Stats</h1>
      <div>
        <form class="form" method="get">
          {{ form }}
          <input type="submit" value="Go">
        </form>
      </div>
    </div>
    {% if their_library %}
    <table class="table">
      <thead>
        <tr id="username">
          <th scope="col"></th>
          <th scope="col" class="field">{{ my_library.user.username }}</th>
          <th scope="col" class="field">Difference</th>
          <th scope="col">{{ their_library.user.username }}</th>
        </tr>
      </thead>
      <tbody>
        <tr id="track-count">
          <th scope="row">Track Count</th>
          <td>{{ my_library.tracks.count }}</td>
          <td>{% calc_diff their_library.tracks.count my_library.tracks.count %}</td>
          <td>{{ their_library.tracks.count }}</td>
        </tr>
        <tr id="artist-count">
          <th scope="row">Artist Count</th>
          <td>{{ my_library.artists.count }}</td>
          <td>{% calc_diff their_library.artists.count my_library.artists.count %}</td>
          <td>{{ their_library.artists.count }}</td>
        </tr>
        {% comment %}
          TODO fix this. is messy and probably has errors.
        {% endcomment %}
        <tr id="total-duration">
          <th scope="row">Total Duration</th>
          <td>{% display_timedelta my_library.total_duration %}</td>
          {% calc_diff my_library.total_duration their_library.total_duration as duration_diff %}
          <td>
            {% display_timedelta duration_diff %}
          </td>
          <td>{% display_timedelta their_library.total_duration %}</td>
        </tr>
      </tbody>
    </table>
    {% endif %}
  </div>
{% endblock content %}

libraries/templates/library_stats.html
{% extends "base.html" %}
{% load date_utils %}
{% block title %}Library: {{ library.user.username }}{% endblock title %}
{% block content %}
    <div class="container">
        <h1 class="text-center" style="padding-bottom:35px">Library Stats</h1>
        {% if form %}
        <div class="text-center" style="padding-bottom:35px">
            <form class="form" method="get">
              {{ form }}
              <input type="submit" value="Go">
            </form>
        </div>
        {% endif %}
        {% if library %}
        {% if not form %}
        <div class="text-center" style="padding-bottom:35px">
            <form action="/pull_data/" class="form" method="POST" style="display:inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary btn-sm text-nowrap">
                    Pull Data
                </button>
            </form>
            <form action="/libraries/compare_stats" class="form" method="GET" style="display:inline">
                <button type="submit" class="btn btn-secondary btn-sm text-nowrap">
                    Compare
                </button>
            </form>
        </div>
        {% endif %}
        <dl class="row properties">
            <dt class="col-sm-3">User</dt>
            <dd class="col-sm-9" id="user-name">
              <a href="{% url 'users:user_info' library.user.pk %}">
                {{ library.user.username }}
              </a>
            </dd>
            <dt class="col-sm-3">Last Updated</dt>
            <dd class="col-sm-9" id="last-updated">
            {% if library.tracks.exists %}
                {{ library.last_updated|date:"F d, Y H:i:s" }}
            {% else %}
                Never
            {% endif %}
            </dd>
            <dt class="col-sm-3">Track Count</dt>
            <dd class="col-sm-9" id="track-count">{{ library.tracks.count }}</dd>
            <dt class="col-sm-3">Artist Count</dt>
            <dd class="col-sm-9" id="artist-count">
                <a href="{% url 'artists:my_artists' %}">
                    {{ library.artists.count }}
                </a>
            </dd>
            <dt class="col-sm-3">Total Duration</dt>
            <dd class="col-sm-9" id="total-duration">{% display_timedelta library.total_duration %}</dd>
            <dt class="col-sm-3">Avg Popularity</dt>
            <dd class="col-sm-9" id="avg-pop">{{ library.avg_pop }}</dd>
            <dt class="col-sm-3">Top Artists</dt>
            <dd class="col-sm-9">
                <ul class="list-group" id="top-artists">
                {% if library.tracks.exists %}
                {% for artist, count in library.top_artists.items %}
                    <li class="list-group-flush artist">
                        <a href="{% url 'artists:single_artist' artist.spotify_id %}">
                            {{ artist.name }} - {{ count }}
                        </a>
                    </li>
                {% endfor %}
                {% else %}
                    None
                {% endif %}
                </ul>
            </dd>
        </dl>
    {% endif %}
    </div>
{% endblock content %}