albums/urls.py
from django.urls import path

from . import views

app_name = 'albums'

urlpatterns = [
    path(r'album_info/<str:album_id>/', views.album_info, name='album_info'),
]

artists/urls.py
from django.urls import path

from . import views

app_name = 'artists'

urlpatterns = [
    path(r'my_artists/', views.all_artists, name='my_artists', kwargs={'mine': True}),
    path(r'all_artists/', views.all_artists, name='all_artists'),
    path(r'user_artists/<str:user_id>/', views.all_artists, name='user_artists'),
    path(r'single_artist/<str:artist_id>/', views.single_artist, name='single_artist'),
]

base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'spotify_login/', views.spotify_login, name='login'),
    path(r'callback/', views.spotify_callback, name='callback'),
    path(r'pull_data/', views.pull_data, name='pull_data'),
    path(r'logout/', views.logout_view, name='logout'),
]

spotify_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('base.urls')),
    re_path(r'^artists/', include('artists.urls')),
    re_path(r'^tracks/', include('tracks.urls')),
    re_path(r'^libraries/', include('libraries.urls')),
    re_path(r'^albums/', include('albums.urls')),
    re_path(r'^users/', include('users.urls')),
    re_path(r'^playlists/', include('playlists.urls')),
]

tracks/urls.py
from django.urls import path

from . import views

app_name = 'tracks'

urlpatterns = [
    path(r'track_info/<str:track_id>/', views.track_info, name='track_info'),
]

tracks/models.py
from datetime import timedelta

from django.db import models


class Track(models.Model):
    objects = models.Manager()
    spotify_id = models.CharField(max_length=100, primary_key=True)
    name = models.CharField(max_length=200)
    artists = models.ManyToManyField('artists.Artist', related_name='tracks')
    album = models.ForeignKey(
        'albums.Album', on_delete=models.CASCADE, related_name='tracks'
    )
    duration_ms = models.CharField(max_length=7)
    is_explicit = models.BooleanField(default=False)
    popularity = models.CharField(max_length=3)
    uri = models.CharField(max_length=100, default="")

    @property
    def duration(self):
        return timedelta(milliseconds=int(self.duration_ms))

tracks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from tracks.models import Track


@login_required
def track_info(request, track_id):
    track = get_object_or_404(Track, pk=track_id)
    return render(
        request,
        'track_info.html',
        {'track': track},
    )

tracks/templates/track_info.html
{% extends "base.html" %}
{% load date_utils %}
{% block title %}Track: {{ track.name }}{% endblock title %}
{% block content %}
    <div class="container">
        <div class="text-center" style="padding-bottom:65px">
            <h1>Track Info</h1>
        </div>
        <dl class="row properties">
            <dt class="col-sm-3">Title</dt>
            <dd class="col-sm-9" id="track-name">{{ track.name }}</dd>
            <dt class="col-sm-3">Artists</dt>
            <dd class="col-sm-9">
                <ul class="list-group" id="artists">
                {% for artist in track.artists.all|dictsort:"name" %}
                    <li class="list-group-flush artist">
                        <a href="{% url 'artists:single_artist' artist.spotify_id %}">
                            {{ artist.name }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            </dd>
            <dt class="col-sm-3">Album</dt>
            <dd class="col-sm-9" id="track-album">
                <a href="{% url 'albums:album_info' track.album.spotify_id %}">
                    {{ track.album }}
                </a>
            </dd>
            <dt class="col-sm-3">ID</dt>
            <dd class="col-sm-9" id="track-id">{{ track.spotify_id }}</dd>
            <dt class="col-sm-3">Duration</dt>
            <dd class="col-sm-9" id="duration">{% display_timedelta_only_mins track.duration %}</dd>
            <dt class="col-sm-3">Explicit</dt>
            <dd class="col-sm-9" id="explicit">{{ track.is_explicit|yesno:"Yes,No" }}</dd>
            <dt class="col-sm-3">Popularity</dt>
            <dd class="col-sm-9" id="popularity">{{ track.popularity }}</dd>
            <dt class="col-sm-3">Uri</dt>
            <dd class="col-sm-9" id="uri">{{ track.uri }}</dd>
        </dl>
    </div>
{% endblock content %}